name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kyosk-config-service:v1.0.0-${GITHUB_SHA::6}-amd64 --build-arg BASE_IMAGE=openjdk:11.0.3-jdk --build-arg APPLICATION_NAME=kyosk-config-service
    - name: Docker Push
      run: docker push  kyosk-config-service:v1.0.0-${GITHUB_SHA::6}-amd64
      
